import { PrismaClient } from "@prisma/client";

const startups = [
  {
    id: "startup-space-city-labs",
    name: "Space City Labs",
    website: "https://spacecitylabs.com",
    description: "Geo tools for Houston logistics and energy.",
    tags: ["geospatial", "energy", "saas"],
    stage: "Series A",
    industry: "Mapping",
    latitude: 29.7499,
    longitude: -95.3584,
    address: "EaDo, Houston, TX"
  },
  {
    id: "startup-bayou-bio",
    name: "Bayou Bio",
    website: "https://bayoubio.com",
    description: "Wet lab automation for gulf coast biomanufacturing.",
    tags: ["biotech", "automation", "seed"],
    stage: "Seed",
    industry: "Biotech",
    latitude: 29.7045,
    longitude: -95.4018,
    address: "Texas Medical Center"
  },
  {
    id: "startup-metro-mobility",
    name: "Metro Mobility",
    website: "https://metromobility.ai",
    description: "AI routing for freight along the I-45 corridor.",
    tags: ["logistics", "ai", "transport"],
    stage: "Pre-Seed",
    industry: "Logistics",
    latitude: 29.7847,
    longitude: -95.3355,
    address: "Northside, Houston, TX"
  },
  {
    id: "startup-cart-com",
    name: "Cart.com",
    website: "https://cart.com",
    description: "Ecommerce operations platform with fulfillment, storefront, and analytics.",
    tags: ["ecommerce", "fulfillment", "series-c"],
    stage: "Series C",
    industry: "Ecommerce",
    latitude: 29.7638,
    longitude: -95.3631,
    address: "Downtown Houston, TX"
  },
  {
    id: "startup-convoz",
    name: "Convoz",
    website: "https://convoz.com",
    description: "Short-form video platform that connects fans with creators and celebrities.",
    tags: ["social", "video", "seed"],
    stage: "Seed",
    industry: "Social",
    latitude: 29.7604,
    longitude: -95.3698,
    address: "Houston, TX"
  },
  {
    id: "startup-ally-energy",
    name: "Ally Energy",
    website: "https://allyenergy.com",
    description: "Career and hiring marketplace for energy transition talent.",
    tags: ["climate", "jobs", "marketplace"],
    stage: "Series A",
    industry: "Climate",
    latitude: 29.758,
    longitude: -95.367,
    address: "Downtown Houston, TX"
  },
  {
    id: "startup-intuitive-machines",
    name: "Intuitive Machines",
    website: "https://www.intuitivemachines.com",
    description: "Lunar lander and space systems company headquartered at the Houston Spaceport.",
    tags: ["aerospace", "space", "public"],
    stage: "Public",
    industry: "Aerospace",
    latitude: 29.5597,
    longitude: -95.0875,
    address: "Houston Spaceport"
  },
  {
    id: "startup-mstack",
    name: "Mstack",
    website: "https://mstack.com",
    description: "Energy software platform for asset data integration and monitoring.",
    tags: ["energy", "saas", "asset-management"],
    stage: "Seed",
    industry: "Energy Software",
    latitude: 29.754,
    longitude: -95.357,
    address: "East Downtown, Houston, TX"
  },
  {
    id: "startup-docjuris",
    name: "DocJuris",
    website: "https://www.docjuris.com",
    description: "Contract negotiation workflow and playbook automation for legal teams.",
    tags: ["legaltech", "contracts", "saas"],
    stage: "Series A",
    industry: "Legal Tech",
    latitude: 29.752,
    longitude: -95.357,
    address: "EaDo, Houston, TX"
  },
  {
    id: "startup-wattbridge",
    name: "WattBridge",
    website: "https://wattbridge.com",
    description: "Fast-start power generation platform building flexible natural gas assets.",
    tags: ["energy", "power", "infrastructure"],
    stage: "Growth",
    industry: "Energy",
    latitude: 29.76,
    longitude: -95.369,
    address: "Houston, TX"
  },
  {
    id: "startup-radial-power",
    name: "Radial Power",
    website: "https://radialpower.com",
    description: "Develops and operates distributed solar and storage projects.",
    tags: ["solar", "energy", "infrastructure"],
    stage: "Growth",
    industry: "Climate",
    latitude: 29.7605,
    longitude: -95.3696,
    address: "Houston, TX"
  },
  {
    id: "startup-utility-global",
    name: "Utility Global",
    website: "https://utility.global",
    description: "Technology to produce low-carbon hydrogen from waste gases and renewables.",
    tags: ["hydrogen", "climate", "industrial"],
    stage: "Series B",
    industry: "Climate Tech",
    latitude: 29.735,
    longitude: -95.472,
    address: "Uptown, Houston, TX"
  },
  {
    id: "startup-thirdai",
    name: "ThirdAI",
    website: "https://thirdai.com",
    description: "Houston AI infrastructure company building efficient training and inference.",
    tags: ["ai", "infrastructure", "series-a"],
    stage: "Series A",
    industry: "AI",
    latitude: 29.717,
    longitude: -95.402,
    address: "Rice University area, Houston, TX"
  },
  {
    id: "startup-axiom-space",
    name: "Axiom Space",
    website: "https://www.axiomspace.com",
    description: "Commercial space station developer supporting private astronaut missions and orbital infrastructure.",
    tags: ["space", "aerospace", "infrastructure"],
    stage: "Growth",
    industry: "Aerospace",
    latitude: 29.5597,
    longitude: -95.0875,
    address: "Houston Spaceport"
  },
  {
    id: "startup-nucamp",
    name: "Nucamp",
    website: "https://www.nucamp.co",
    description: "Affordable coding bootcamps delivered through hybrid online and local cohorts.",
    tags: ["edtech", "bootcamp", "coding"],
    stage: "Growth",
    industry: "EdTech",
    latitude: 29.7604,
    longitude: -95.3698,
    address: "Houston, TX"
  },
  {
    id: "startup-graylog",
    name: "Graylog",
    website: "https://graylog.org",
    description: "Security and log management platform for observability and threat detection.",
    tags: ["security", "observability", "saas"],
    stage: "Series C",
    industry: "Security",
    latitude: 29.7608,
    longitude: -95.3697,
    address: "Downtown Houston, TX"
  },
  {
    id: "startup-highradius",
    name: "HighRadius",
    website: "https://www.highradius.com",
    description: "AI-powered order-to-cash and treasury management software.",
    tags: ["fintech", "ai", "saas"],
    stage: "Growth",
    industry: "Fintech",
    latitude: 29.957,
    longitude: -95.419,
    address: "North Houston, TX"
  },
  {
    id: "startup-hello-alice",
    name: "Hello Alice",
    website: "https://helloalice.com",
    description: "Platform offering grants, funding access, and resources for small business owners.",
    tags: ["small-business", "fintech", "marketplace"],
    stage: "Series C",
    industry: "Fintech",
    latitude: 29.749,
    longitude: -95.358,
    address: "EaDo, Houston, TX"
  },
  {
    id: "startup-onit",
    name: "Onit",
    website: "https://www.onit.com",
    description: "Enterprise legal management and contract automation software.",
    tags: ["legaltech", "saas", "enterprise"],
    stage: "Growth",
    industry: "Legal Tech",
    latitude: 29.7602,
    longitude: -95.3695,
    address: "Downtown Houston, TX"
  },
  {
    id: "startup-riversand",
    name: "Riversand",
    website: "https://www.riversand.com",
    description: "Master data management and product information management platform.",
    tags: ["data", "mdm", "saas"],
    stage: "Growth",
    industry: "Enterprise Software",
    latitude: 29.735,
    longitude: -95.472,
    address: "Uptown, Houston, TX"
  },
  {
    id: "startup-beyond-finance",
    name: "Beyond Finance",
    website: "https://www.beyondfinance.com",
    description: "Debt resolution fintech helping consumers consolidate and settle debt.",
    tags: ["fintech", "consumer", "debt"],
    stage: "Growth",
    industry: "Fintech",
    latitude: 29.7604,
    longitude: -95.37,
    address: "Houston, TX"
  },
  {
    id: "startup-majority",
    name: "MAJORITY",
    website: "https://www.majority.com",
    description: "Mobile banking and community services tailored for immigrants.",
    tags: ["fintech", "banking", "immigrant"],
    stage: "Series B",
    industry: "Fintech",
    latitude: 29.744,
    longitude: -95.389,
    address: "Montrose, Houston, TX"
  },
  {
    id: "startup-lancium",
    name: "Lancium",
    website: "https://lancium.com",
    description: "Grid-scale computing and renewable-powered data centers that stabilize the grid.",
    tags: ["energy", "data-centers", "climate"],
    stage: "Growth",
    industry: "Energy",
    latitude: 29.7605,
    longitude: -95.36,
    address: "Houston, TX"
  },
  {
    id: "startup-tekrevol",
    name: "TekRevol",
    website: "https://www.tekrevol.com",
    description: "Product development studio building mobile, web, and cloud software.",
    tags: ["services", "software", "agency"],
    stage: "Growth",
    industry: "Software Services",
    latitude: 29.748,
    longitude: -95.37,
    address: "Downtown Houston, TX"
  },
  {
    id: "startup-goexpedi",
    name: "GoExpedi",
    website: "https://www.goexpedi.com",
    description: "Industrial and energy MRO procurement marketplace with logistics and analytics.",
    tags: ["marketplace", "energy", "logistics"],
    stage: "Series C",
    industry: "Industrial",
    latitude: 29.753,
    longitude: -95.359,
    address: "Houston, TX"
  },
  {
    id: "startup-recode-solutions",
    name: "Recode Solutions",
    website: "https://recodesolutions.com",
    description: "Custom software and product development consultancy.",
    tags: ["services", "consulting", "software"],
    stage: "Growth",
    industry: "Software Services",
    latitude: 29.73,
    longitude: -95.43,
    address: "Houston, TX"
  },
  {
    id: "startup-sage-geosystems",
    name: "Sage Geosystems",
    website: "https://sagegeosystems.com",
    description: "Geothermal energy storage and power technology company.",
    tags: ["geothermal", "energy", "climate"],
    stage: "Series A",
    industry: "Energy",
    latitude: 29.736,
    longitude: -95.47,
    address: "Houston, TX"
  },
  {
    id: "startup-fluidity-technologies",
    name: "Fluidity Technologies",
    website: "https://www.fluidity.tech",
    description: "Precision motion controllers and joysticks for aerospace and robotics.",
    tags: ["aerospace", "hardware", "control"],
    stage: "Growth",
    industry: "Aerospace",
    latitude: 29.552,
    longitude: -95.095,
    address: "Houston, TX"
  },
  {
    id: "startup-cognitive-space",
    name: "Cognitive Space",
    website: "https://www.cognitivespace.com",
    description: "AI-driven mission management and tasking platform for satellite constellations.",
    tags: ["space", "ai", "satellites"],
    stage: "Series A",
    industry: "Aerospace",
    latitude: 29.7607,
    longitude: -95.3696,
    address: "Downtown Houston, TX"
  },
  {
    id: "startup-c3-ai",
    name: "C3 AI",
    website: "https://c3.ai",
    description: "Enterprise AI platform for predictive maintenance, ESG, and supply chain analytics.",
    tags: ["ai", "enterprise", "public"],
    stage: "Public",
    industry: "AI",
    latitude: 29.7605,
    longitude: -95.3698,
    address: "Houston, TX"
  },
  {
    id: "startup-koda-health",
    name: "Koda Health",
    website: "https://www.kodahealthcare.com",
    description: "Advance care planning and patient engagement platform for healthcare providers.",
    tags: ["healthtech", "saas", "patient-engagement"],
    stage: "Seed",
    industry: "Health Tech",
    latitude: 29.716,
    longitude: -95.401,
    address: "Texas Medical Center, Houston, TX"
  },
  {
    id: "startup-disco",
    name: "DISCO",
    website: "https://csdisco.com",
    description: "Cloud-native eDiscovery and legal case management platform.",
    tags: ["legaltech", "saas", "public"],
    stage: "Public",
    industry: "Legal Tech",
    latitude: 29.7604,
    longitude: -95.37,
    address: "Houston, TX"
  },
  {
    id: "startup-ltv-ai",
    name: "LTV.ai",
    website: "https://www.ltv.ai",
    description: "AI platform to predict and grow customer lifetime value for ecommerce brands.",
    tags: ["ai", "ecommerce", "analytics"],
    stage: "Seed",
    industry: "AI",
    latitude: 29.757,
    longitude: -95.365,
    address: "Downtown Houston, TX"
  },
  {
    id: "startup-adaptive-ai",
    name: "Adaptive AI LLC",
    website: "https://adaptiveai.ai",
    description: "AI solutions company delivering predictive models and automation for enterprises.",
    tags: ["ai", "automation", "services"],
    stage: "Seed",
    industry: "AI Services",
    latitude: 29.753,
    longitude: -95.359,
    address: "Houston, TX"
  },
  {
    id: "startup-innovapptive",
    name: "Innovapptive",
    website: "https://www.innovapptive.com",
    description: "Connected worker and field operations platform for industrial companies.",
    tags: ["industrial", "saas", "mobile"],
    stage: "Growth",
    industry: "Industrial Software",
    latitude: 29.735,
    longitude: -95.472,
    address: "Uptown, Houston, TX"
  },
  {
    id: "startup-opro-ai",
    name: "oPRO.ai Inc",
    website: "https://opro.ai",
    description: "AI-driven optimization and robotics software for industrial operations.",
    tags: ["ai", "industrial", "automation"],
    stage: "Seed",
    industry: "Industrial AI",
    latitude: 29.751,
    longitude: -95.37,
    address: "Houston, TX"
  },
  {
    id: "startup-orchestra-macrosystems",
    name: "Orchestra Macrosystems",
    website: "https://orchestramacro.com",
    description: "Data integration and analytics platform for industrial and energy systems.",
    tags: ["data", "industrial", "analytics"],
    stage: "Seed",
    industry: "Industrial Software",
    latitude: 29.74,
    longitude: -95.4,
    address: "Houston, TX"
  },
  {
    id: "startup-little-place-labs",
    name: "Little Place Labs",
    website: "https://littleplacelabs.com",
    description: "Edge software to process satellite data for maritime and logistics monitoring.",
    tags: ["space", "edge", "analytics"],
    stage: "Seed",
    industry: "Aerospace",
    latitude: 29.7602,
    longitude: -95.3689,
    address: "Houston, TX"
  }
];

export const seedStartups = async (prisma: PrismaClient) => {
  for (const startup of startups) {
    await prisma.startup.upsert({
      where: { id: startup.id },
      update: { ...startup, tags: JSON.stringify(startup.tags) },
      create: { ...startup, tags: JSON.stringify(startup.tags) }
    });
  }
};
